from django import forms

# MODELS
from apps.accommodation.models.room.room_model import Room
from apps.accommodation.models.floor.floor_model import Floor
from apps.accommodation.models.bed.bed_configuration import BedConfiguration

# SHARE UTILITY FORM
from apps.core.forms import StyledFormMixin


class RoomForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Room
        fields = (
            "floor",
            "position",
            "bed_configuration_override",
        )

    def clean_position(self):
        position = self.cleaned_data["position"]

        if position < 1:
            raise forms.ValidationError(
                "Room position must be at least 1."
            )

        return position


class CreateRoomForm(StyledFormMixin, forms.Form):
    """
    Room position is generated by RoomService.

    The user supplies the floor and optional configuration override.
    """

    floor = forms.ModelChoiceField(
        queryset=Floor.objects.all(),
    )

    bed_configuration_override = forms.ModelChoiceField(
        queryset=BedConfiguration.objects.active(),
        required=False,
    )


class RoomBedConfigurationForm(StyledFormMixin, forms.Form):
    bed_configuration = forms.ModelChoiceField(
        queryset=BedConfiguration.objects.active(),
        required=False,
    )