# Generated by Django 5.2.13 on 2026-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_verified_user_is_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('ADMIN', 'Administrator')], help_text='Designates the role and permission of the user in the system', max_length=20),
        ),
    ]
