# Generated by Django 5.2.13 on 2026-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='The code could be the abbreviation of the university name', max_length=20, verbose_name='University Code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='University Name')),
                ('website', models.URLField(blank=True, verbose_name='University Website')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['-name'],
            },
        ),
    ]
